/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Administrator
 */
public class Form_Add_Edit_Account extends javax.swing.JFrame implements ActionListener{

    private Account account = null;
    /**
     * Creates new form Form_Add_Edit_Account
     */
    public Form_Add_Edit_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lab_form_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_form_website_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_form_user = new javax.swing.JTextField();
        txt_form_pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_form_submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Giao Diện Thêm Mới/Chỉnh Sửa Tài Khoản ");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lab_form_name.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lab_form_name.setForeground(new java.awt.Color(255, 0, 0));
        lab_form_name.setText("Giao Diện Thêm Mới Tài Khoản");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Tên Website");

        txt_form_website_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txt_form_website_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_form_website_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Tên Đăng Nhập");

        txt_form_user.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txt_form_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_form_userActionPerformed(evt);
            }
        });

        txt_form_pass.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txt_form_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_form_passActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Mật Khẩu");

        btn_form_submit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_form_submit.setText("Thêm Mới");

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_form_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_form_website_name)
                    .addComponent(txt_form_user)
                    .addComponent(txt_form_pass)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_form_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_form_name)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_form_website_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_form_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_form_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_form_submit)
                    .addComponent(jButton1))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_form_website_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_form_website_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_form_website_nameActionPerformed

    private void txt_form_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_form_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_form_userActionPerformed

    private void txt_form_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_form_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_form_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        reset_data();
        reset_info("Giao Diện Thêm Mới Tài Khoản", "Thêm Mới");
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_form_submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_form_name;
    private javax.swing.JTextField txt_form_pass;
    private javax.swing.JTextField txt_form_user;
    private javax.swing.JTextField txt_form_website_name;
    // End of variables declaration//GEN-END:variables

    
    public Account getAccountInfo(){
        String website_name = txt_form_website_name.getText();
        String username = txt_form_user.getText();
        String password = txt_form_pass.getText();
        
        //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
     
        if(account == null){
            return new Account(-1, website_name, username, password,date,1);
        }else{
            account.setUsername(username);
            account.setWebsite(website_name);
            account.setPassword(password);
            return account;
        }
    }
    
    public void btnAccountListenner(ActionListener log){
        btn_form_submit.addActionListener(log);
    }
    
    
    public void reset_data(){
        txt_form_website_name.setText("");
        txt_form_user.setText("");
        txt_form_pass.setText("");
    }
    
    public void setData(Account account){
        this.account = account;
        if(account != null){
            txt_form_website_name.setText(account.getWebsite());
            txt_form_user.setText(account.getUsername());
            txt_form_pass.setText(account.getPassword());
        }
    }
    
    public void reset_info(String title, String btn_text){
        lab_form_name.setText(title);
        btn_form_submit.setText(btn_text);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
